# Generated by Django 3.0.6 on 2020-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(max_length=255, null=True, upload_to='picture/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
